# Generated by Django 4.1.4 on 2022-12-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_order_total_price_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total Price'),
        ),
    ]
